fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      # for future parser tests with puppet < 4
      ref: "4.25.1"
    alternatives:
      repo: "https://github.com/puppet-community/puppet-alternatives"
      # ruby 1.9.3 compatibility
      ref: "3.0.0"
    hadoop_lib: "https://github.com/MetaCenterCloudPuppet/cesnet-hadoop_lib"
  symlinks:
    hadoop: "#{source_dir}"
