name 'cesnet-hadoop'
version '2.0.0'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-hadoop'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'Hadoop Cluster with security'
description 'Hadoop Cluster with security'
project_page 'https://github.com/MetaCenterCloudPuppet'

dependency 'puppetlabs/stdlib', '>= 1.0.0 <5.0.0'
dependency 'adrien/alternatives', '>= 0.3.0 <1.0.0'
