name 'cesnet-hadoop'
version '0.9.5'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-hadoop'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'Hadoop Cluster with security'
description 'Hadoop Cluster with security'
project_page 'https://github.com/MetaCenterCloudPuppet'

dependency 'puppetlabs/stdlib'
dependency 'adrien/alternatives'
