name 'cesnet-hadoop'
version '2.4.3'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-hadoop'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'Hadoop Cluster with security'
description 'Hadoop Cluster with security'
project_page 'https://github.com/MetaCenterCloudPuppet/cesnet-hadoop'

dependency 'puppetlabs/stdlib', '>= 1.0.0 <5.0.0'
dependency 'cesnet/hadoop_lib', '<1.0.0'
